apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app.fullname" . }}  # "name" is imported from the helper function
  labels:  # They are added for identification of service sectors
    app: {{ include "todo-app.name" . }}
    chart: {{ include "todo-app.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}  # Corrected indentation here
  selector:
    matchLabels:  # Corrected indentation here
      app: {{ include "todo-app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:  # Corrected indentation here
      labels:
        app: {{ include "todo-app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "todo-app.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}  # Ensuring proper indentation
