apiVersion:v1
kind: Services 
metadata:
  name: {{ include "todo-app.fullname" . }}
  labels:
    app: {{ include "todo-app.name" . }}
spec:
  type: {{ .Values.service.type }}  
  ports:
      name: http
    - port: {{ .Values.service.port }}
      targetPort: {{ .Value.service.post}}
      protocol: TCP
  selector:
    app: {{ include "todo-app.name" . }}
    release: {{ .Release.Name }}